"""
作者         xupeng
邮箱         874582705@qq.com / 15601598009@163.com
github主页   https://github.com/xupeng1206

"""

# 整理一些写死的字符串，方便后续修改

FLANGER_URLS = 'FLANGER_URLS'

URL_PREFIX = 'url_prefix'

BASE_DIR = 'BASE_DIR'

FLANGER_REQUEST_PROCESSORS = 'FLANGER_REQUEST_PROCESSORS'

FLANGER_RESPONSE_PROCESSORS = 'FLANGER_RESPONSE_PROCESSORS'

SWAGGER_IGNORE_PARAMS = 'SWAGGER_IGNORE_PARAMS'

FLANGER_SWAGGER_ENDPOINT = 'Base.SwaggerResource'
